---
- name: Install http
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - httpd-devel
   - httpd-tools
   - git
   
- name: http service state
  service: name=httpd state=started enabled=yes

- name: restart httpd
  service: name=httpd state=restarted

