- name: Configure webserver with nginx
  hosts: webservers
  become: True
  tasks:
    - name: install nginx
      dnf: name=nginx state=latest

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/

    - name: copy index.html
      template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: enable at startup and restart nginx
      service: name=nginx enabled=yes state=restarted
