---
- hosts: all
  roles:
  - common

- hosts: dbservers
  roles:
  - db
  tags:
  - db

- hosts: webservers
  roles:
  - base-apache
  - web
  - php
  tags:
  - web

- hosts: lbservers

  roles:
  - haproxy
  
  tags:
  - lb
