---
- name: Ensure dependencies
  package: "name={{ item }} state=installed"
  with_items:
    - autoconf
    - re2c
    - flex-devel
    - automake
    - libtool
    - bison
    - make
    - curl-devel
    - recode-devel
    - aspell-devel
    - libxml2-devel
    - pkgconfig
    - libmcrypt-devel
    - t1lib-devel
    - libXpm-devel
    - libpng-devel
    - libjpeg-turbo-devel
    - bzip2-devel
    - openssl-devel
    - freetype-devel
    - libicu-devel
    - mysql-devel
    #- mariadb-devel
    - gmp-devel
    - libtool-ltdl-devel
    - libxml2-devel
    - openssl-devel
    - curl-devel
    - libmcrypt-devel
    - libidn-devel
    - libjpeg-devel
    - gcc-c++
    - libpng-devel
    - freetype-devel
    - bzip2-devel
    - libxslt-devel
    - autoconf
    - aspell-devel
    - libtidy-devel
    - libc-client-devel
    - libmcrypt-devel
    - aspell-devel
    - libxslt-devel
    - libtool
    - bzip2-devel
    - libXpm-devel
    - libmcrypt
    - mysql-devel
    - pcre-devel

  when: ansible_os_family == 'RedHat'

- name: Check if gmp.h is already in a location accessible to gcc.
  stat: path=/usr/include/gmp.h
  register: gmp_file

- name: Ensure gmp.h is symlinked into a location accessible to gcc.
  file:
    src: "{{ php_source_install_gmp_path }}"
    dest: /usr/include/gmp.h
    state: link
  when: gmp_file.stat.exists == false

- name: Check if PHP is installed.
  command: which php
  changed_when: false
  failed_when: false
  register: php_installed

- name: Clone the PHP repository.
  git:
    repo: https://git.php.net/repository/php-src.git
    dest: "{{ php_source_clone_dir }}"
    version: "{{ php_source_version }}"
    accept_hostkey: yes
    force: yes
    #depth: "{{ php_source_clone_depth }}"
  when: php_installed|failed

- name: Ensure PHP installation path exists.
  file:
    path: "{{ php_source_install_path }}"
    state: directory
    mode: 0755
  when: php_installed|failed

- name: Build configure script.
  shell: "./buildconf --force"
  args: 
        executable: /bin/bash
        chdir: "{{ php_source_clone_dir }}"
        
  when: php_installed|failed

- name: Run configure script.
  shell: "{{ php_source_configure_command }}"
  args:
    executable: /bin/bash
    chdir: "{{ php_source_clone_dir }}"
  when: php_installed|failed

- name: Make and install PHP.
  shell: >
    chdir={{ php_source_clone_dir }}
    {{ item }}
  with_items:
    - "{{ php_source_make_command }}"
    - make install
  when: php_installed|failed

- name: Ensure php executable is symlinked into a standard path.
  file:
    src: "{{ php_source_install_path }}/bin/php"
    dest: /usr/bin/php
    state: link

