- name: show return value of command module
  gather_facts: True
  hosts: all
  tasks:
    - name: capture output of id command
      command: id -un
      register: login
    #- debug: var=login

    - debug: msg="Logged in as user {{ login.stdout }}"

    - debug: var=ansible_distribution

